version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter
    steps:
      - checkout
      - run:
          working_directory: app
          command: |
            flutter doctor
            flutter test
            flutter -v build apk
      - run: |
          working_directory: app
          curl \
            -H "Authorization: token ${DG_TOKEN}" \
            -F "file=@build/app/outputs/apk/app.apk" \
            -F "message=${CIRCLE_SHA1}" \
            "https://deploygate.com/api/users/${DG_USER}/apps"
